package com.christopherosthues.starwarsprogressbar.ui

import com.christopherosthues.starwarsprogressbar.StarWarsBundle.message
import com.christopherosthues.starwarsprogressbar.constants.BundleConstants
import com.christopherosthues.starwarsprogressbar.constants.ImageResourceConstants
import com.intellij.util.containers.stream
import java.awt.Color
import java.util.stream.Collectors

internal enum class StarWarsVehicle(
    val fileName: String,
    val vehicleName: String,
    val faction: Faction,
    val color: Color,
    val xShift: Int,
    val yShift: Int,
    val velocity: Float = 2.5f,
    val acceleration: Float = 1f
) {
    // TODO: set individual velocity of all vehicles
    ACCLAMATOR_CLASS_ASSAULT_SHIP(
        ImageResourceConstants.ACCLAMATOR_CLASS_ASSAULT_SHIP,
        message(BundleConstants.ACCLAMATOR_CLASS_ASSAULT_SHIP),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        -7,
        -6
    ),
    ARC_170_STARFIGHTER(
        ImageResourceConstants.ARC_170_STARFIGHTER,
        message(BundleConstants.ARC_170_STARFIGHTER),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.RedEngine,
        -12,
        -6
    ),
    AZURE_ANGEL(
        ImageResourceConstants.AZURE_ANGEL,
        message(BundleConstants.AZURE_ANGEL),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.RedEngine,
        -10,
        -6
    ),
    BERENKO_CLASS_GONDOLA_SPEEDER(
        ImageResourceConstants.BERENKO_CLASS_GONDOLA_SPEEDER,
        message(BundleConstants.BERENKO_CLASS_GONDOLA_SPEEDER),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        -10,
        -6,
        0.75f
    ),
    BLADE_OF_DORIN(
        ImageResourceConstants.BLADE_OF_DORIN,
        message(BundleConstants.BLADE_OF_DORIN),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.RedEngine,
        -6,
        -6
    ),
    DC0052_SPEEDER(
        ImageResourceConstants.DC0052_SPEEDER,
        message(BundleConstants.DC0052_SPEEDER),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        -13,
        -6
    ),
    DELTA_7_JEDI_STARFIGHTER(
        ImageResourceConstants.DELTA_7_JEDI_STARFIGHTER,
        message(BundleConstants.DELTA_7_JEDI_STARFIGHTER),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        -4,
        -6
    ),
    ETA_2_ACTIS_INTERCEPTOR(
        ImageResourceConstants.ETA_2_ACTIS_INTERCEPTOR,
        message(BundleConstants.ETA_2_ACTIS_INTERCEPTOR),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        -6,
        -6
    ),
    H_TYPE_NABOO_YACHT(
        ImageResourceConstants.H_TYPE_NABOO_YACHT,
        message(BundleConstants.H_TYPE_NABOO_YACHT),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        -4,
        -6
    ),
    J_TYPE_DIPLOMATIC_BARGE(
        ImageResourceConstants.J_TYPE_DIPLOMATIC_BARGE,
        message(BundleConstants.J_TYPE_DIPLOMATIC_BARGE),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        -14,
        -6
    ),
    J_TYPE_NABOO_STAR_SKIFF(
        ImageResourceConstants.J_TYPE_NABOO_STAR_SKIFF,
        message(BundleConstants.J_TYPE_NABOO_STAR_SKIFF),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        -14,
        -6
    ),
    N_1_STARFIGHTER(
        ImageResourceConstants.N_1_STARFIGHTER,
        message(BundleConstants.N_1_STARFIGHTER),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        -16,
        -6
    ),
    NABOO_ROYAL_STARSHIP(
        ImageResourceConstants.NABOO_ROYAL_STARSHIP,
        message(BundleConstants.NABOO_ROYAL_STARSHIP),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        -6,
        -6
    ),
    V_WING(
        ImageResourceConstants.V_WING,
        message(BundleConstants.V_WING),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.YellowEngine,
        -4,
        -6
    ),
    VENATOR_CLASS_STAR_DESTROYER(
        ImageResourceConstants.VENATOR_CLASS_STAR_DESTROYER,
        message(BundleConstants.VENATOR_CLASS_STAR_DESTROYER),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        0,
        -6
    ),
    V_19_TORRENT_STARFIGHTER(
        ImageResourceConstants.V_19_TORRENT_STARFIGHTER,
        message(BundleConstants.V_19_TORRENT_STARFIGHTER),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.BlueEngine,
        -10,
        -6
    ),
    Z_95_HEADHUNTER(
        ImageResourceConstants.Z_95_HEADHUNTER,
        message(BundleConstants.Z_95_HEADHUNTER),
        Faction.GALACTIC_REPUBLIC,
        IonEngineColor.RedEngine,
        -9,
        -6
    ),

    BLODDFIN(
        ImageResourceConstants.BLODDFIN,
        message(BundleConstants.BLOODFIN),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.GreenEngine,
        -4,
        -6
    ),
    DIAMOND_CLASS_CRUISER(
        ImageResourceConstants.DIAMOND_CLASS_CRUISER,
        message(BundleConstants.DIAMOND_CLASS_CRUISER),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.YellowEngine,
        -12,
        -6
    ),
    DROID_TRI_FIGHTER(
        ImageResourceConstants.DROID_TRI_FIGHTER,
        message(BundleConstants.DROID_TRI_FIGHTER),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.YellowEngine,
        -3,
        -6
    ),
    FANBLADE(
        ImageResourceConstants.FANBLADE,
        message(BundleConstants.FANBLADE),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.YellowEngine,
        -12,
        -6
    ),
    IG_227_HAILFIRE_CLASS_DROID_TANK(
        ImageResourceConstants.IG_227_HAILFIRE_CLASS_DROID_TANK,
        message(BundleConstants.IG_227_HAILFIRE_CLASS_DROID_TANK),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.BrownEngine,
        -8,
        -6
    ),
    INVISIBLE_HAND(
        ImageResourceConstants.INVISIBLE_HAND,
        message(BundleConstants.INVISIBLE_HAND),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.BlueEngine,
        0,
        -6
    ),
    LUCREHULK_CLASS_BATTLESHIP(
        ImageResourceConstants.LUCREHULK_CLASS_BATTLESHIP,
        message(BundleConstants.LUCREHULK_CLASS_BATTLESHIP),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.BlueEngine,
        -6,
        -6
    ),
    MANKVIM_814_INTERCEPTOR(
        ImageResourceConstants.MANKVIM_814_INTERCEPTOR,
        message(BundleConstants.MANKVIM_814_INTERCEPTOR),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.BlueEngine,
        -6,
        -6
    ),
    MTT(
        ImageResourceConstants.MTT,
        message(BundleConstants.MTT),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.YellowEngine,
        0,
        -6,
        0.5f
    ),
    MUNIFICENT_CLASS_STAR_FRIGATE(
        ImageResourceConstants.MUNIFICENT_CLASS_STAR_FRIGATE,
        message(BundleConstants.MUNIFICENT_CLASS_STAR_FRIGATE),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.YellowEngine,
        -3,
        -6
    ),
    NANTEX_CLASS_STARFIGHTER(
        ImageResourceConstants.NANTEX_CLASS_STARFIGHTER,
        message(BundleConstants.NANTEX_CLASS_STARFIGHTER),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.BlueEngine,
        0,
        -6
    ),
    PLATOON_ATTACK_CRAFT(
        ImageResourceConstants.PLATOON_ATTACK_CRAFT,
        message(BundleConstants.PLATOON_ATTACK_CRAFT),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.BlueEngine,
        0,
        -6
    ),
    PORAX_38_STARFIGHTER(
        ImageResourceConstants.PORAX_38_STARFIGHTER,
        message(BundleConstants.PORAX_38_STARFIGHTER),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.YellowEngine,
        -10,
        -6
    ),
    RECUSANT_CLASS_DESTROYER(
        ImageResourceConstants.RECUSANT_CLASS_DESTROYER,
        message(BundleConstants.RECUSANT_CLASS_DESTROYER),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.YellowEngine,
        -2,
        -6
    ),
    SEPARATIST_SUPPLY_SHIP(
        ImageResourceConstants.SEPARATIST_SUPPLY_SHIP,
        message(BundleConstants.SEPARATIST_SUPPLY_SHIP),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.YellowEngine,
        -10,
        -6
    ),
    SOULLESS_ONE(
        ImageResourceConstants.SOULLESS_ONE,
        message(BundleConstants.SOULLESS_ONE),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.YellowEngine,
        -12,
        -6
    ),
    STAP(
        ImageResourceConstants.STAP,
        message(BundleConstants.STAP),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.YellowEngine,
        -12,
        -6
    ),
    TRADE_FEDERATION_LANDING_SHIP(
        ImageResourceConstants.TRADE_FEDERATION_LANDING_SHIP,
        message(BundleConstants.TRADE_FEDERATION_LANDING_SHIP),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.RedEngine,
        -12,
        -6
    ),
    VULTURE_DROID(
        ImageResourceConstants.VULTURE_DROID,
        message(BundleConstants.VULTURE_DROID),
        Faction.CONFEDERACY_OF_INDEPENDENT_SYSTEMS,
        IonEngineColor.RedEngine,
        -12,
        -6
    ),

    A_WING(
        ImageResourceConstants.A_WING,
        message(BundleConstants.A_WING),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.RedEngine,
        -4,
        -6,
        5f
    ),
    B_WING(
        ImageResourceConstants.B_WING,
        message(BundleConstants.B_WING),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.RedEngine,
        -13,
        -6,
        2.5f
    ),
    GR_75_TRANSPORT(
        ImageResourceConstants.GR_75_TRANSPORT,
        message(BundleConstants.GR_75_TRANSPORT),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.BlueEngine,
        0,
        -6
    ),
    HOME_ONE(
        ImageResourceConstants.HOME_ONE,
        message(BundleConstants.HOME_ONE),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.BlueEngine,
        -2,
        -6
    ),
    MC80_LIBERTY_STAR_CRUISER(
        ImageResourceConstants.MC80_LIBERTY_STAR_CRUISER,
        message(BundleConstants.MC80_LIBERTY_STAR_CRUISER),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.BlueEngine,
        -9,
        -6
    ),
    MILLENNIUM_FALCON(
        ImageResourceConstants.MILLENNIUM_FALCON,
        message(BundleConstants.MILLENNIUM_FALCON),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.BlueEngine,
        -16,
        -6,
        5f
    ),
    NEBULON_B_FRIGATE(
        ImageResourceConstants.NEBULON_B_FRIGATE,
        message(BundleConstants.NEBULON_B_FRIGATE),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.BlueEngine,
        -1,
        -6
    ),
    ROGUE_SHADOW(
        ImageResourceConstants.ROGUE_SHADOW,
        message(BundleConstants.ROGUE_SHADOW),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.BlueEngine,
        -8,
        -6
    ),
    TANTIVE_IV(
        ImageResourceConstants.TANTIVE_IV,
        message(BundleConstants.TANTIVE_IV),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.RedEngine,
        0,
        -6
    ),
    T_47_SNOWSPEEDER(
        ImageResourceConstants.T_47_SNOWSPEEDER,
        message(BundleConstants.T_47_SNOWSPEEDER),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.WhiteEngine,
        -9,
        -6
    ),
    U_WING(
        ImageResourceConstants.U_WING,
        message(BundleConstants.U_WING),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.BlueEngine,
        0,
        -6,
        4f
    ),
    X_WING(
        ImageResourceConstants.X_WING,
        message(BundleConstants.X_WING),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.RedEngine,
        -4,
        -6,
        4f
    ),
    Y_WING(
        ImageResourceConstants.Y_WING,
        message(BundleConstants.Y_WING),
        Faction.REBEL_ALLIANCE,
        IonEngineColor.RedEngine,
        -2,
        -6,
        2f
    ),

    ECLIPSE(
        ImageResourceConstants.ECLIPSE,
        message(BundleConstants.ECLIPSE),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BlueEngine,
        -2,
        -6
    ),
    EXECUTOR(
        ImageResourceConstants.EXECUTOR,
        message(BundleConstants.EXECUTOR),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BlueEngine,
        -8,
        -6
    ),
    FIRST_DEATH_STAR(
        ImageResourceConstants.FIRST_DEATH_STAR,
        message(BundleConstants.FIRST_DEATH_STAR),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.GreenEngine,
        -12,
        -6,
        1f
    ),
    IMPERIAL_CLASS_STAR_DESTROYER(
        ImageResourceConstants.IMPERIAL_CLASS_STAR_DESTROYER,
        message(BundleConstants.IMPERIAL_CLASS_STAR_DESTROYER),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BlueEngine,
        -1,
        -6
    ),
    INTERDICTOR_CLASS_STAR_DESTROYER(
        ImageResourceConstants.INTERDICTOR_CLASS_STAR_DESTROYER,
        message(BundleConstants.INTERDICTOR_CLASS_STAR_DESTROYER),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BlueEngine,
        -5,
        -6
    ),
    LAMBDA_CLASS_SHUTTLE(
        ImageResourceConstants.LAMBDA_CLASS_SHUTTLE,
        message(BundleConstants.LAMBDA_CLASS_SHUTTLE),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BlueEngine,
        -13,
        -6
    ),
    SECOND_DEATH_STAR(
        ImageResourceConstants.SECOND_DEATH_STAR,
        message(BundleConstants.SECOND_DEATH_STAR),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.GreenEngine,
        -12,
        -6,
        1f
    ),
    SENTINEL_CLASS_SHUTTLE(
        ImageResourceConstants.SENTINEL_CLASS_SHUTTLE,
        message(BundleConstants.SENTINEL_CLASS_SHUTTLE),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BlueEngine,
        -8,
        -6
    ),
    TARTAN_CLASS_PATROL_CRUISER(
        ImageResourceConstants.TARTAN_CLASS_PATROL_CRUISER,
        message(BundleConstants.TARTAN_CLASS_PATROL_CRUISER),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BlueEngine,
        0,
        -6
    ),
    THETA_CLASS_SHUTTLE(
        ImageResourceConstants.THETA_CLASS_SHUTTLE,
        message(BundleConstants.THETA_CLASS_SHUTTLE),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BlueEngine,
        -12,
        -6
    ),
    TIE_BOMBER(
        ImageResourceConstants.TIE_BOMBER,
        message(BundleConstants.TIE_BOMBER),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BlueEngine,
        -8,
        -6,
        2.5f
    ),
    TIE_CRAWLER(
        ImageResourceConstants.TIE_CRAWLER,
        message(BundleConstants.TIE_CRAWLER),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BrownEngine,
        -8,
        -6
    ),
    TIE_FIGHTER(
        ImageResourceConstants.TIE_FIGHTER,
        message(BundleConstants.TIE_FIGHTER),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BlueEngine,
        -16,
        -6,
        4.5f
    ),
    TIE_INTERCEPTOR(
        ImageResourceConstants.TIE_INTERCEPTOR,
        message(BundleConstants.TIE_INTERCEPTOR),
        Faction.GALACTIC_EMPIRE,
        IonEngineColor.BlueEngine,
        -9,
        -6,
        4.5f
    ),

    BOBA_FETTS_SLAVE_ONE(
        ImageResourceConstants.BOBA_FETTS_SLAVE_ONE,
        message(BundleConstants.BOBA_FETTS_SLAVE_ONE),
        Faction.BOUNTY_HUNTERS,
        IonEngineColor.RedEngine,
        -12,
        -6,
        4.75f
    ),
    IG_2000(
        ImageResourceConstants.IG_2000,
        message(BundleConstants.IG_2000),
        Faction.BOUNTY_HUNTERS,
        IonEngineColor.BlueEngine,
        -8,
        -6
    ),
    JANGO_FETTS_SLAVE_ONE(
        ImageResourceConstants.JANGO_FETTS_SLAVE_ONE,
        message(BundleConstants.JANGO_FETTS_SLAVE_ONE),
        Faction.BOUNTY_HUNTERS,
        IonEngineColor.RedEngine,
        -12,
        -6,
        4.75f
    ),

    CLOUD_CITY(
        ImageResourceConstants.CLOUD_CITY,
        message(BundleConstants.CLOUD_CITY),
        Faction.SMUGGLERS,
        IonEngineColor.OrangeEngine,
        -16,
        -6,
        1f
    ),
    ERRANT_VENTURE(
        ImageResourceConstants.ERRANT_VENTURE,
        message(BundleConstants.ERRANT_VENTURE),
        Faction.SMUGGLERS,
        IonEngineColor.BlueEngine,
        -1,
        -6
    ),

    ANAKIN_SKYWALKERS_PODRACER(
        ImageResourceConstants.ANAKIN_SKYWALKERS_PODRACER,
        message(BundleConstants.ANAKIN_SKYWALKERS_PODRACER),
        Faction.PODRACER,
        IonEngineColor.PurpleEngine,
        -14,
        -6,
        4.5f
    ),
    SEBULBAS_PODRACER(
        ImageResourceConstants.SEBULBAS_PODRACER,
        message(BundleConstants.SEBULBAS_PODRACER),
        Faction.PODRACER,
        IonEngineColor.PurpleEngine,
        -14,
        -6,
        4f
    ),

    MISSING(
        ImageResourceConstants.MISSING,
        message(BundleConstants.MISSING),
        Faction.NONE,
        IonEngineColor.GreenEngine,
        -4,
        -6
    );

    companion object {
        @JvmField
        var DEFAULT_VEHICLES: List<StarWarsVehicle> =
            values().stream().filter { v: StarWarsVehicle -> v != MISSING }.collect(Collectors.toList())
    }
}
