package com.christopherosthues.starwarsprogressbar.configuration

internal fun createStarWarsProgressConfigurationComponent(): StarWarsProgressConfigurationComponent = StarWarsProgressConfigurationComponent()
