package com.christopherosthues.starwarsprogressbar.constants

internal object BundleConstants {
    const val PLUGIN_NAME = "name"

    private const val CONFIGURATION = "configuration."
    const val PREVIEW_TITLE = CONFIGURATION + "preview"
    const val DETERMINATE = CONFIGURATION + "determinate"
    const val INDETERMINATE = CONFIGURATION + "indeterminate"
    const val UI_OPTIONS = CONFIGURATION + "uiOptions"
    const val SHOW_VEHICLE_NAME = CONFIGURATION + "showVehicleName"
    const val SHOW_TOOL_TIPS = CONFIGURATION + "showToolTips"
    const val SAME_VEHICLE_VELOCITY = CONFIGURATION + "sameVehicleVelocity"
    const val VEHICLES_TITLE = CONFIGURATION + "vehicles"
    const val SELECT_ALL = CONFIGURATION + "selectAll"
    const val DESELECT_ALL = CONFIGURATION + "deselectAll"
    const val SELECTED = CONFIGURATION + "selected"

    const val FACTION = "faction."
    const val GALACTIC_REPUBLIC = FACTION + "galactic_republic"
    const val CONFEDERACY_OF_INDEPENDENT_SYSTEMS = FACTION + "confederacy_of_independent_systems"
    const val GALACTIC_EMPIRE = FACTION + "galactic_empire"
    const val REBEL_ALLIANCE = FACTION + "rebel_alliance"
    const val BOUNTY_HUNTERS = FACTION + "bounty_hunters"
    const val SMUGGLERS = FACTION + "smugglers"
    const val PODRACER = FACTION + "podracer"

    const val VEHICLES = "vehicles."
    const val ACCLAMATOR_CLASS_ASSAULT_SHIP = VEHICLES + "acclamator_class_assault_ship"
    const val ARC_170_STARFIGHTER = VEHICLES + "arc_170_starfighter"
    const val AZURE_ANGEL = VEHICLES + "azure_angel"
    const val BERENKO_CLASS_GONDOLA_SPEEDER = VEHICLES + "berenko_class_gondola_speeder"
    const val BLADE_OF_DORIN = VEHICLES + "blade_of_dorin"
    const val DC0052_SPEEDER = VEHICLES + "dc0052_speeder"
    const val DELTA_7_JEDI_STARFIGHTER = VEHICLES + "delta_7_jedi_starfighter"
    const val ETA_2_ACTIS_INTERCEPTOR = VEHICLES + "eta_2_actis_interceptor"
    const val H_TYPE_NABOO_YACHT = VEHICLES + "h_type_naboo_yacht"
    const val J_TYPE_DIPLOMATIC_BARGE = VEHICLES + "j_type_diplomatic_barge"
    const val J_TYPE_NABOO_STAR_SKIFF = VEHICLES + "j_type_naboo_star_skiff"
    const val N_1_STARFIGHTER = VEHICLES + "n_1_starfighter"
    const val NABOO_ROYAL_STARSHIP = VEHICLES + "naboo_royal_starship"
    const val V_WING = VEHICLES + "v_wing"
    const val VENATOR_CLASS_STAR_DESTROYER = VEHICLES + "venator_class_star_destroyer"
    const val V_19_TORRENT_STARFIGHTER = VEHICLES + "v_19_torrent_starfighter"
    const val Z_95_HEADHUNTER = VEHICLES + "z_95_headhunter"

    const val BLOODFIN = VEHICLES + "bloodfin"
    const val DIAMOND_CLASS_CRUISER = VEHICLES + "diamond_class_cruiser"
    const val DROID_TRI_FIGHTER = VEHICLES + "droid_tri_fighter"
    const val FANBLADE = VEHICLES + "fanblade"
    const val IG_227_HAILFIRE_CLASS_DROID_TANK = VEHICLES + "ig_227_hailfire_class_droid_tank"
    const val INVISIBLE_HAND = VEHICLES + "invisible_hand"
    const val LUCREHULK_CLASS_BATTLESHIP = VEHICLES + "lucrehulk_class_battleship"
//    const val MALEVOLENCE = VEHICLES + "malevolence"
    const val MANKVIM_814_INTERCEPTOR = VEHICLES + "mankvim_814_interceptor"
    const val MTT = VEHICLES + "mtt"
    const val MUNIFICENT_CLASS_STAR_FRIGATE = VEHICLES + "munificent_class_star_frigate"
    const val NANTEX_CLASS_STARFIGHTER = VEHICLES + "nantex_class_starfighter"
    const val PLATOON_ATTACK_CRAFT = VEHICLES + "platoon_attack_craft"
    const val PORAX_38_STARFIGHTER = VEHICLES + "porax_38_starfighter"
    const val RECUSANT_CLASS_DESTROYER = VEHICLES + "recusant_class_destroyer"
    const val SEPARATIST_SUPPLY_SHIP = VEHICLES + "separatist_supply_ship"
    const val SOULLESS_ONE = VEHICLES + "soulless_one"
    const val STAP = VEHICLES + "stap"
    const val TRADE_FEDERATION_LANDING_SHIP = VEHICLES + "trade_federation_landing_ship"
    const val VULTURE_DROID = VEHICLES + "vulture_droid"

    const val A_WING = VEHICLES + "a_wing"
    const val B_WING = VEHICLES + "b_wing"
    const val GR_75_TRANSPORT = VEHICLES + "gr_75_transport"
    const val HOME_ONE = VEHICLES + "home_one"
    const val MC80_LIBERTY_STAR_CRUISER = VEHICLES + "mc80_liberty_star_cruiser"
    const val MILLENNIUM_FALCON = VEHICLES + "millennium_falcon"
    const val NEBULON_B_FRIGATE = VEHICLES + "nebulon_b_frigate"
    const val ROGUE_SHADOW = VEHICLES + "rogue_shadow"
    const val TANTIVE_IV = VEHICLES + "tantive_iv"
    const val T_47_SNOWSPEEDER = VEHICLES + "t_47_snowspeeder"
    const val U_WING = VEHICLES + "u_wing"
    const val X_WING = VEHICLES + "x_wing"
    const val Y_WING = VEHICLES + "y_wing"

    const val ECLIPSE = VEHICLES + "eclipse"
    const val EXECUTOR = VEHICLES + "executor"
    const val FIRST_DEATH_STAR = VEHICLES + "first_death_star"
    const val IMPERIAL_CLASS_STAR_DESTROYER = VEHICLES + "imperial_class_star_destroyer"
    const val INTERDICTOR_CLASS_STAR_DESTROYER = VEHICLES + "interdictor_class_star_destroyer"
    const val LAMBDA_CLASS_SHUTTLE = VEHICLES + "lambda_class_shuttle"
    const val SECOND_DEATH_STAR = VEHICLES + "second_death_star"
    const val SENTINEL_CLASS_SHUTTLE = VEHICLES + "sentinel_class_shuttle"
    const val TARTAN_CLASS_PATROL_CRUISER = VEHICLES + "tartan_class_patrol_cruiser"
    const val THETA_CLASS_SHUTTLE = VEHICLES + "theta_class_shuttle"
    const val TIE_BOMBER = VEHICLES + "tie_bomber"
    const val TIE_CRAWLER = VEHICLES + "tie_crawler"
    const val TIE_FIGHTER = VEHICLES + "tie_fighter"
    const val TIE_INTERCEPTOR = VEHICLES + "tie_interceptor"

    const val BOBA_FETTS_SLAVE_ONE = VEHICLES + "boba_fetts_slave_one"
    const val IG_2000 = VEHICLES + "ig_2000"
    const val JANGO_FETTS_SLAVE_ONE = VEHICLES + "jango_fetts_slave_one"

    const val CLOUD_CITY = VEHICLES + "cloud_city"
    const val ERRANT_VENTURE = VEHICLES + "errant_venture"

    const val ANAKIN_SKYWALKERS_PODRACER = VEHICLES + "anakin_skywalkers_podracer"
    const val SEBULBAS_PODRACER = VEHICLES + "sebulbas_podracer"

    const val MISSING = VEHICLES + "missing"
}
