package com.christopherosthues.starwarsprogressbar.constants

internal object ImageResourceConstants {
    private const val REPUBLIC = "republic/"
    const val ACCLAMATOR_CLASS_ASSAULT_SHIP = REPUBLIC + "acclamator_class_assault_ship"
    const val ARC_170_STARFIGHTER = REPUBLIC + "arc_170_starfighter"
    const val AZURE_ANGEL = REPUBLIC + "azure_angel"
    const val BERENKO_CLASS_GONDOLA_SPEEDER = REPUBLIC + "berenko_class_gondola_speeder"
    const val BLADE_OF_DORIN = REPUBLIC + "blade_of_dorin"
    const val DC0052_SPEEDER = REPUBLIC + "dc0052_speeder"
    const val DELTA_7_JEDI_STARFIGHTER = REPUBLIC + "delta_7_jedi_starfighter"
    const val ETA_2_ACTIS_INTERCEPTOR = REPUBLIC + "eta_2_actis"
    const val H_TYPE_NABOO_YACHT = REPUBLIC + "h_type_naboo_yacht"
    const val J_TYPE_DIPLOMATIC_BARGE = REPUBLIC + "j_type_diplomatic_barge"
    const val J_TYPE_NABOO_STAR_SKIFF = REPUBLIC + "j_type_naboo_star_skiff"
    const val N_1_STARFIGHTER = REPUBLIC + "n_1_starfighter"
    const val NABOO_ROYAL_STARSHIP = REPUBLIC + "naboo_royal_starship"
    const val V_WING = REPUBLIC + "v_wing"
    const val VENATOR_CLASS_STAR_DESTROYER = REPUBLIC + "venator_class_star_destroyer"
    const val V_19_TORRENT_STARFIGHTER = REPUBLIC + "v_19_torrent_starfighter"
    const val Z_95_HEADHUNTER = REPUBLIC + "z_95_headhunter"

    private const val SEPARATISTS = "separatists/"
    const val BLODDFIN = SEPARATISTS + "bloodfin"
    const val DIAMOND_CLASS_CRUISER = SEPARATISTS + "diamond_class_cruiser"
    const val DROID_TRI_FIGHTER = SEPARATISTS + "droid_tri_fighter"
    const val FANBLADE = SEPARATISTS + "fanblade"
    const val IG_227_HAILFIRE_CLASS_DROID_TANK = SEPARATISTS + "ig_227_hailfire_class_droid_tank"
    const val INVISIBLE_HAND = SEPARATISTS + "invisible_hand"
    const val LUCREHULK_CLASS_BATTLESHIP = SEPARATISTS + "droid_control_ship"
    const val MANKVIM_814_INTERCEPTOR = SEPARATISTS + "mankvim_814_interceptor"
    const val MTT = SEPARATISTS + "multi_troop_transport"
    const val MUNIFICENT_CLASS_STAR_FRIGATE = SEPARATISTS + "munificent_class_star_frigate"
    const val NANTEX_CLASS_STARFIGHTER = SEPARATISTS + "nantex_class_starfighter"
    const val PLATOON_ATTACK_CRAFT = SEPARATISTS + "platoon_attack_craft"
    const val PORAX_38_STARFIGHTER = SEPARATISTS + "porax_38_starfighter"
    const val RECUSANT_CLASS_DESTROYER = SEPARATISTS + "recusant_class_destroyer"
    const val SEPARATIST_SUPPLY_SHIP = SEPARATISTS + "separatist_supply_ship"
    const val SOULLESS_ONE = SEPARATISTS + "soulless_one"
    const val STAP = SEPARATISTS + "stap"
    const val TRADE_FEDERATION_LANDING_SHIP = SEPARATISTS + "trade_federation_landing_ship"
    const val VULTURE_DROID = SEPARATISTS + "vulture_droid"

    private const val ALLIANCE = "alliance/"
    const val A_WING = ALLIANCE + "a_wing"
    const val B_WING = ALLIANCE + "b_wing"
    const val GR_75_TRANSPORT = ALLIANCE + "gr_75_transport"
    const val HOME_ONE = ALLIANCE + "home_one"
    const val MC80_LIBERTY_STAR_CRUISER = ALLIANCE + "mc80_liberty_star_cruiser"
    const val MILLENNIUM_FALCON = ALLIANCE + "millennium_falcon"
    const val NEBULON_B_FRIGATE = ALLIANCE + "nebulon_b_frigate"
    const val ROGUE_SHADOW = ALLIANCE + "rogue_shadow"
    const val TANTIVE_IV = ALLIANCE + "tantive_iv"
    const val T_47_SNOWSPEEDER = ALLIANCE + "t_47_snowspeeder"
    const val U_WING = ALLIANCE + "u_wing"
    const val X_WING = ALLIANCE + "x_wing"
    const val Y_WING = ALLIANCE + "y_wing"

    private const val EMPIRE = "empire/"
    const val ECLIPSE = EMPIRE + "eclipse"
    const val EXECUTOR = EMPIRE + "executor"
    const val FIRST_DEATH_STAR = EMPIRE + "firstst_death_star"
    const val IMPERIAL_CLASS_STAR_DESTROYER = EMPIRE + "imperial_class_star_destroyer"
    const val INTERDICTOR_CLASS_STAR_DESTROYER = EMPIRE + "interdictor_class_star_destroyer"
    const val LAMBDA_CLASS_SHUTTLE = EMPIRE + "lambda_class_shuttle"
    const val SECOND_DEATH_STAR = EMPIRE + "second_death_star"
    const val SENTINEL_CLASS_SHUTTLE = EMPIRE + "sentinel_class_shuttle"
    const val TARTAN_CLASS_PATROL_CRUISER = EMPIRE + "tartan_class_patrol_cruiser"
    const val THETA_CLASS_SHUTTLE = EMPIRE + "theta_class_shuttle"
    const val TIE_BOMBER = EMPIRE + "tie_bomber"
    const val TIE_CRAWLER = EMPIRE + "tie_crawler"
    const val TIE_FIGHTER = EMPIRE + "tie_fighter"
    const val TIE_INTERCEPTOR = EMPIRE + "tie_interceptor"

    private const val BOUNTY_HUNTER = "bountyhunter/"
    const val BOBA_FETTS_SLAVE_ONE = BOUNTY_HUNTER + "boba_fetts_slave_one"
    const val IG_2000 = BOUNTY_HUNTER + "ig_2000"
    const val JANGO_FETTS_SLAVE_ONE = BOUNTY_HUNTER + "jango_fetts_slave_one"

    private const val SMUGGLER = "smuggler/"
    const val CLOUD_CITY = SMUGGLER + "cloud_city"
    const val ERRANT_VENTURE = SMUGGLER + "errant_venture"

    private const val PODRACER = "podracer/"
    const val ANAKIN_SKYWALKERS_PODRACER = PODRACER + "anakin_skywalkers_podracer"
    const val SEBULBAS_PODRACER = PODRACER + "sebulbas_podracer"

    const val MISSING = "missing"
}
