package com.christopherosthues.starwarsprogressbar.constants

internal object ImageResourceConstants {
    const val ACCLAMATOR_CLASS_ASSAULT_SHIP = "acclamator_class_assault_ship"
    const val ARC_170_STARFIGHTER = "arc_170_starfighter"
    const val AZURE_ANGEL = "azure_angel"
    const val BERENKO_CLASS_GONDOLA_SPEEDER = "berenko_class_gondola_speeder"
    const val BLADE_OF_DORIN = "blade_of_dorin"
    const val DC0052_SPEEDER = "dc0052_speeder"
    const val DELTA_7_JEDI_STARFIGHTER = "delta_7_jedi_starfighter"
    const val ETA_2_ACTIS_INTERCEPTOR = "eta_2_actis"
    const val H_TYPE_NABOO_YACHT = "h_type_naboo_yacht"
    const val J_TYPE_DIPLOMATIC_BARGE = "j_type_diplomatic_barge"
    const val J_TYPE_NABOO_STAR_SKIFF = "j_type_naboo_star_skiff"
    const val N_1_STARFIGHTER = "n_1_starfighter"
    const val NABOO_ROYAL_STARSHIP = "naboo_royal_starship"
    const val V_WING = "v_wing"
    const val VENATOR_CLASS_STAR_DESTROYER = "venator_class_star_destroyer"
    const val V_19_TORRENT_STARFIGHTER = "v_19_torrent_starfighter"
    const val Z_95_HEADHUNTER = "z_95_headhunter"

    const val BLODDFIN = "bloodfin"
    const val DIAMOND_CLASS_CRUISER = "diamond_class_cruiser"
    const val DROID_TRI_FIGHTER = "droid_tri_fighter"
    const val FANBLADE = "fanblade"
    const val IG_227_HAILFIRE_CLASS_DROID_TANK = "ig_227_hailfire_class_droid_tank"
    const val INVISIBLE_HAND = "invisible_hand"
    const val LUCREHULK_CLASS_BATTLESHIP = "droid_control_ship"
    const val MANKVIM_814_INTERCEPTOR = "mankvim_814_interceptor"
    const val MTT = "multi_troop_transport"
    const val MUNIFICENT_CLASS_STAR_FRIGATE = "munificent_class_star_frigate"
    const val NANTEX_CLASS_STARFIGHTER = "nantex_class_starfighter"
    const val PLATOON_ATTACK_CRAFT = "platoon_attack_craft"
    const val PORAX_38_STARFIGHTER = "porax_38_starfighter"
    const val RECUSANT_CLASS_DESTROYER = "recusant_class_destroyer"
    const val SEPARATIST_SUPPLY_SHIP = "separatist_supply_ship"
    const val SOULLESS_ONE = "soulless_one"
    const val STAP = "stap"
    const val TRADE_FEDERATION_LANDING_SHIP = "trade_federation_landing_ship"
    const val VULTURE_DROID = "vulture_droid"

    const val A_WING = "a_wing"
    const val B_WING = "b_wing"
    const val GR_75_TRANSPORT = "gr_75_transport"
    const val HOME_ONE = "home_one"
    const val MC80_LIBERTY_STAR_CRUISER = "mc80_liberty_star_cruiser"
    const val MILLENNIUM_FALCON = "millennium_falcon"
    const val NEBULON_B_FRIGATE = "nebulon_b_frigate"
    const val ROGUE_SHADOW = "rogue_shadow"
    const val TANTIVE_IV = "tantive_iv"
    const val T_47_SNOWSPEEDER = "t_47_snowspeeder"
    const val U_WING = "u_wing"
    const val X_WING = "x_wing"
    const val Y_WING = "y_wing"

    const val ECLIPSE = "eclipse"
    const val EXECUTOR = "executor"
    const val FIRST_DEATH_STAR = "1st_death_star"
    const val IMPERIAL_CLASS_STAR_DESTROYER = "imperial_class_star_destroyer"
    const val INTERDICTOR_CLASS_STAR_DESTROYER = "interdictor_class_star_destroyer"
    const val LAMBDA_CLASS_SHUTTLE = "lambda_class_shuttle"
    const val SECOND_DEATH_STAR = "2nd_death_star"
    const val SENTINEL_CLASS_SHUTTLE = "sentinel_class_shuttle"
    const val TARTAN_CLASS_PATROL_CRUISER = "tartan_class_patrol_cruiser"
    const val THETA_CLASS_SHUTTLE = "theta_class_shuttle"
    const val TIE_BOMBER = "tie_bomber"
    const val TIE_CRAWLER = "tie_crawler"
    const val TIE_FIGHTER = "tie_fighter"
    const val TIE_INTERCEPTOR = "tie_interceptor"

    const val BOBA_FETTS_SLAVE_ONE = "boba_fetts_slave_one"
    const val IG_2000 = "ig_2000"
    const val JANGO_FETTS_SLAVE_ONE = "jango_fetts_slave_one"

    const val CLOUD_CITY = "cloud_city"
    const val ERRANT_VENTURE = "errant_venture"

    const val ANAKIN_SKYWALKERS_PODRACER = "anakin_skywalkers_podracer"
    const val SEBULBAS_PODRACER = "sebulbas_podracer"

    const val MISSING = "missing"
}
